export const BANNER_COMMENT = `
/* eslint-disable */
/**
 * This file was automatically generated by apify-misterious-tool.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run apify-misterious-tool to regenerate this file.
 */
`;
